# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='\u59d3\u540d')),
                ('major', models.CharField(max_length=200, verbose_name='\u4e13\u4e1a')),
                ('phone_num', models.CharField(max_length=200, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('qq', models.CharField(max_length=200, verbose_name='QQ')),
                ('first_choice', models.CharField(max_length=200, verbose_name='\u7b2c\u4e00\u5fd7\u613f')),
                ('second_choice', models.CharField(max_length=200, verbose_name='\u7b2c\u4e8c\u5fd7\u613f')),
                ('recognize', models.TextField(verbose_name='\u5bf9\u79d1\u534f\u7684\u8ba4\u8bc6')),
                ('introduction', models.TextField(verbose_name='\u81ea\u6211\u4ecb\u7ecd')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-pub_date',),
                'verbose_name': '\u62a5\u540d\u4fe1\u606f',
                'verbose_name_plural': '\u62a5\u540d\u4fe1\u606f',
            },
        ),
    ]
