# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signmessage',
            name='first_choice',
            field=models.CharField(choices=[('\u7f51\u7edc\u90e8', '\u7f51\u7edc\u90e8'), ('\u521b\u4e1a\u90e8', '\u521b\u4e1a\u90e8'), ('\u7ade\u8d5b\u90e8', '\u7ade\u8d5b\u90e8'), ('\u793e\u56e2\u90e8', '\u793e\u56e2\u90e8')], max_length=200, verbose_name='\u7b2c\u4e00\u5fd7\u613f'),
        ),
        migrations.AlterField(
            model_name='signmessage',
            name='major',
            field=models.CharField(choices=[('\u7f51\u7edc\u5de5\u7a0b', '\u7f51\u7edc\u5de5\u7a0b'), ('\u4fe1\u606f\u5b89\u5168', '\u4fe1\u606f\u5b89\u5168'), ('\u8ba1\u7b97\u79d1\u5b66\u4e0e\u6280\u672f', '\u8ba1\u7b97\u673a\u79d1\u5b66\u4e0e\u6280\u672f'), ('\u7269\u8054\u7f51\u5de5\u7a0b', '\u7269\u8054\u7f51\u5de5\u7a0b'), ('\u8f6f\u4ef6\u5de5\u7a0b', '\u8f6f\u4ef6\u5de5\u7a0b')], max_length=200, verbose_name='\u4e13\u4e1a'),
        ),
        migrations.AlterField(
            model_name='signmessage',
            name='second_choice',
            field=models.CharField(choices=[('\u7f51\u7edc\u90e8', '\u7f51\u7edc\u90e8'), ('\u521b\u4e1a\u90e8', '\u521b\u4e1a\u90e8'), ('\u7ade\u8d5b\u90e8', '\u7ade\u8d5b\u90e8'), ('\u793e\u56e2\u90e8', '\u793e\u56e2\u90e8')], max_length=200, verbose_name='\u7b2c\u4e8c\u5fd7\u613f'),
        ),
    ]
