# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0003_auto_20170807_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signmessage',
            name='phone_num',
            field=models.IntegerField(default=1, verbose_name='\u7535\u8bdd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signmessage',
            name='qq',
            field=models.IntegerField(verbose_name='QQ'),
        ),
    ]
