# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUp', '0004_auto_20170808_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signmessage',
            name='phone_num',
            field=models.CharField(max_length=200, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='signmessage',
            name='qq',
            field=models.CharField(max_length=200, verbose_name='QQ'),
        ),
    ]
